service: celeb-network-api

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1  # or your region
  stage: dev
  environment:
    JWT_SECRET: 'your_secret_key'
    DB_URL: 'postgres://username:password@host:port/dbname'

functions:
  api:
    handler: dist/main.handler
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true

plugins:
  - serverless-webpack
  - serverless-offline

package:
  individually: false
  excludeDevDependencies: true

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
